DELETE http://localhost:3001/api/podaci/60342108f96c5f5e5c7abe71
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbW8iLCJpZCI6IjYwMzQwYTUzZGFlYmNlMmIzOGRmYzI5ZCIsImlhdCI6MTYxNDA5NzI0Mn0.mbBX_LZt3JJtAo2J_xr4SwNtn77zACjjWzuht5SQhcI
